### ISSUE TITLE
USB Detection

### ISSUE THREAD

**Issue by thelittlemike** [brouberol/pico-mixer#1]
So I feel like I'm so close yet so far in getting this to work. I followed the instructions and get the web server to run, get the Pico to light up pastel type colors when plugged in, but cannot for the life of me get rid of the red circle with a slash telling me the Pico is not connected. I'm not great with Python so I was wondering where I could check. I know in your write-up on your blog, you mentioned the location of the Pico under Mac/Linux but Windows doesn't do /dev/ttyUSB0 etc. (I'm on Windows).

Also, another thing to note, in your instructions you say to move your sounds over to the sounds folder. However, there are two of them. one in the pico-mixer-main folder and another in the pico_mixer_web\assets folder. The sounds should be moved under assets and that wasn't clear. Putting them in the pico-mixer-main\sounds results in a 404.

Anyway, any help you can provide would rock. If I can get the USB detection on Windows settled, I'd be good.

Also feature request: Modifier key. This way you can toggle between sounds and sound effects. Or even open up the possibility of more sounds by having an entire second (third, fourth, etc) set of buttons.

Anyway, thanks for your hard work. This is awesome!

**Comment by thelittlemike** [comment]
Found the issue!
In app.py line 14: ADAFRUIT_HARDWARE_VENDOR_ID
The hardware ID in your code did not match what I saw in Device Manager in Windows. For me, it was 239A:8120. Changed that and like magic everything is now working.

This is so awesome! Thanks again for this!

**Comment by brouberol** [comment]
Thanks so much for the report, the investigation and the kind words! I'm very glad you got it working. I will integrate the VENDOR_ID you reported in the codebase, alongside "mine", to make sure things work out of the box for more people.

**Comment by brouberol** [comment]
Actually even better, according to https://devicehunt.com/view/type/usb/vendor/239A, the vendor ID is `239A`, which is common between the one I hardcoded and the one you reported. That will make things easier.

**Comment by brouberol** [comment]
Fixed in 9a6e3d0

**Comment by thelittlemike** [comment]
> Actually even better, according to https://devicehunt.com/view/type/usb/vendor/239A, the vendor ID is `239A`, which is common between the one I hardcoded and the one you reported. That will make things easier.

Sweet! Thanks again! And you are very welcome!
