### ISSUE TITLE
Audio files immediately show 100% and don't play.

### ISSUE THREAD

**Issue by joeybarrus** [brouberol/pico-mixer#2]
Hi Balthazar,
My son found your excellent pico mixer project and asked me to help him assemble it for his D&D Campaign's. We've completed everything, however I've come across a couple of problems and I'm hoping you can steer me in the right direction. 

1. I created a few audio files and dropped them into the 'sounds' folder in the root folder. But I was getting a 404 response. Moving the sounds folder into pico_mixer_web/assets seems to have resolved this. However...
2. Although the application seems to find the files now, once I update config.js, the web interface no longer receives the color information and audio files still don't play. The progress immediately goes to 100% and no audio plays.

I'm on Mac OSX m1 running Python 3.10.5 and pygame (2.1.2) was failing to install so I upgraded it to 2.4.0. I'm not sure if that's causing the issues or maybe another oversight. Let me know if you have any ideas, thanks!

![interface-contected-no-color](https://github.com/brouberol/pico-mixer/assets/4803658/5e97017a-7a81-44a0-9161-fe6f2b1ddec3)
![audio-files-found](https://github.com/brouberol/pico-mixer/assets/4803658/b0ce0fbe-f308-4050-a18f-3cdbde35ff61)
![sounds-folder-404](https://github.com/brouberol/pico-mixer/assets/4803658/f959aba8-56a0-4c40-bec9-9a2afab8cef1)

**Comment by joeybarrus** [comment]
I came back a week later and everything is working. I guess my terminal code probably just needed a restart. Disregard!

**Comment by brouberol** [comment]
Oops, sorry, I'm just seeing this issue now!

> But I was getting a 404 response. Moving the sounds folder into pico_mixer_web/assets seems to have resolved this

Yes, that's my fault. The latest version of the code should make sure to have ` pico_mixer_web/assets/sounds` point to the `sounds` directory at the root of the project.

As to the other issue, I'm not sure what happened, but I'm sure glad everything is working now!
